# File Transfer Harness Configuration

# Global settings
output_dir: ./output

# Job definitions
jobs:
  - name: http_upload_job
    type: http
    enabled: true
    config:
      url: "https://example.com/upload"
      method: POST
      username: "http_user"  # Username for authentication and tracking
      directory: "./files_to_upload"
      initial_rate: "10/hour"  # Start at 10 files per hour
      target_rate: "60/hour"   # Ramp up to 60 files per hour
      ramp_rate: "10/hour"     # Increase by 10 files per hour
      ssl:
        cert_path: "/path/to/cert.pem"
        key_path: "/path/to/key.pem"
      headers:
        Content-Type: "application/octet-stream"
        X-Transaction-Id: "{{uuid}}"  # Replaced with generated UUID
        X-Filename: "{{filename}}"    # Replaced with current filename
        X-Username: "{{username}}"    # Replaced with configured username

  - name: sftp_upload_job
    type: sftp
    enabled: true
    config:
      host: "sftp.example.com"
      port: 22
      username: "sftp_user"  # Username for authentication and tracking
      key_path: "/path/to/ssh_key"  # Either key_path or password
      # password: "secret"          # Uncomment to use password auth
      directory: "./files_to_upload"
      remote_path: "/uploads"
      initial_rate: "30/hour"
      target_rate: "30/hour"
      ramp_rate: "5/hour"       # Optional: Increase rate by this amount